<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_Halaman_Profile</name>
   <tag></tag>
   <elementGuidId>bb6e09ef-0146-407e-b52a-aef670dc5ede</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div[3]/div/div/div[2]/div/div[1]/nav/div/div/div[3]/div[2]/div/div[2]/div/div/a[1]/div/div[2]/div/div/div[1]/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
